[platformio]
src_dir = src

[env:feather_rp2040_can]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_can
framework = arduino
extra_scripts = pre:../scripts/platformio_sync_profile.py
custom_profile_path = ../platformio_profile.h
custom_example_profile_path = ../platformio_profile.example.h
custom_version_path = ../VERSION
board_build.core = earlephilhower
lib_deps = autowp/autowp-mcp2515
build_flags =
    -I../include
    -I..
    -DDRIVER_MCP2515

[env:feather_m4_can]
platform = atmelsam
board = adafruit_feather_m4_can
framework = arduino
extra_scripts = pre:../scripts/platformio_sync_profile.py
custom_profile_path = ../platformio_profile.h
custom_example_profile_path = ../platformio_profile.example.h
custom_version_path = ../VERSION
lib_deps = adafruit/Adafruit CAN
build_flags =
    -I../include
    -I..
    -DDRIVER_SAME51
    -std=gnu++17
build_unflags = -std=gnu++11
